trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'Docker Hub - 4lch4'
    repository: '4lch4/app_homepage'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    containerRegistry: 'Docker Hub - 4lch4'
    repository: '4lch4/app_homepage'
    command: 'push'