trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: custom
    customCommand: 'ci'

- task: Npm@1
  displayName: 'Build dist folder'
  inputs:
    command: 'custom'
    customCommand: 'run build:prod'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'Docker Hub - 4lch4'
    repository: '4lch4/app_homepage'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    containerRegistry: 'Docker Hub - 4lch4'
    repository: '4lch4/app_homepage'
    command: 'push'

- powershell: |
   $WHURL = "$(DISCORD_WH_URL)"
   
   $ReqBody = @{
     content = "$(Build.QueuedBy) queued a build for the $(Build.Repository.Name) repository on the ``$(Build.SourceBranchName)`` branch.";
     embeds = @(
       @{
         title = '$(Build.DefinitionName)';
         description = "Build on ``$(Build.SourceBranchName)`` branch has completed.";
         url = 'https://dev.azure.com/4lch4/Ansel/_build/results?buildId=$(Build.BuildId)';
         fields = @(
           @{
             name = 'Job Status';
             value = '$(Agent.JobStatus)';
           },
           @{
             name = 'Build Id';
             value = '$(Build.BuildId)';
           }
         )
       }
     )
   }
   
   $Json = $ReqBody | ConvertTo-Json -Depth 10 -Compress
   
   Write-Host $Json
   
   Invoke-RestMethod -Uri $WHURL -Method Post -ContentType 'application/json' -Body $Json
  errorActionPreference: continue
  displayName: 'Send Discord Webhook Message'